---
title: "Modelos ETS"
author: "Sam"
format: html
editor: visual
---

```{r}
#| message: false
library(tidyverse)
library(fpp3)
library(tsibble)
library(feasts)
library(fable)
```

```{r}
manufactura <- tidyquant::tq_get(
  "MEXPRMNTO01IXOBM",
  get = "economic.data",
  from = "1980-01-01"
) |> 
  mutate(
    date = yearmonth(date)
  ) |> 
  as_tsibble(index = date)

manufactura_train <- manufactura |> 
  filter_index(. ~ '2023 mar')

autoplot(manufactura)
```

```{r}
manufactura_fit <- manufactura_train |>
  model(
    snaive = SNAIVE(log(price)),
    drift  = RW(log(price) ~ drift()),
    stlf = decomposition_model(
          STL(log(price) ~ season(window = "periodic"), robust = TRUE),
          RW(season_adjust ~ drift())
        ),
    ETS = ETS(log(price))
  )

manufactura_fit
```

```{r}
manufactura_fit |>
  augment() |>
  features(.innov, ljung_box, lag = 24)
```

```{r}
manufactura_fcst <- manufactura_fit |> 
  forecast(h = 12) 

manufactura_fcst |> 
  autoplot(manufactura |> 
             filter_index('2020 jan'~ .)
           ) +
  facet_wrap(~.model, ncol = 2)
```

```{r}
manufactura_fcst |> 
  accuracy(manufactura) |> 
  select(.model:.type, MAE) |> 
  arrange(MAE)
```
